### PR TITLE
Create lifecycle_stage field on BatchTrial

### PR DESCRIPTION
**Pull request by danielcohenlive**
Summary: This is in preparation for quickBO, where trials will require lifecycle_stage

Differential Revision: D35249204

### CODE REVIEW

**Comment by Padarn** [comment]
hi @danielcohenlive could you give any more details about `QuickBO`?

**Comment by eytan** [comment]
QuickBO is a method / experimental design that we use for AB tests which
uses multi-task models to extrapolate long-term outcomes from sequences of
short run and long run experiments. Happy to share a brief tech report on
this if you email me.

**Comment by Padarn** [comment]
I definitely will. Thank you.

**Comment by Padarn** [comment]
Sent an email to your @fb.com account. Let me know if that is no longer valid. Cheers.

**Pull request closed without merging**
