### PR TITLE
Update input_constructors and re-enable KG/MES for modular BotAx

### PR DESCRIPTION
**Pull request by j-wilson**
Summary: `ax` part of T104296884

Reviewed By: Balandat

Differential Revision: D32302518

### CODE REVIEW

**Comment by Balandat** [comment]
Hmm the test failures are likely caused by the recent merge of https://github.com/cornellius-gp/gpytorch/pull/1737

**Comment by paoloBerizzi** [comment]
Hi, any updates on that? I'm also trying to implement a multi-fidelity model and the absence of MFKG and MFMES in `input_constructors` is preventing me from doing so. Do you plan to plan to re-enable KG/MES soon, perhaps referring to [BoTorch v0.6.1](https://github.com/pytorch/botorch/releases/tag/v0.6.1)?

**Comment by j-wilson** [comment]
How up to date is your `botorch` package? The dispatches you mentioned should have been added to `input_constructors` in [BoTorch #984](https://github.com/pytorch/botorch/pull/984/commits) and be included in v0.6.1 (despite our failure to mention them in the changelog). Can you please confirm whether you are having issues with these features in v0.6.1?

**Comment by paoloBerizzi** [comment]
> 

I'm working with Ax v0.2.3 that depends on botorch v0.6.0. If I force the use of botorch v0.6.1 there will be conflict in the dependencies.

**Comment by saitcakmak** [comment]
Hi @paoloBerizzi. Ax is about to release a new version that will depend on botorch 0.6.1. I believe that will resolve the issue. In the meantime, you can try installing the latest (current github main) version of Ax: https://github.com/facebook/Ax#latest-version

**Comment by paoloBerizzi** [comment]
Thanks, that's exactly what I was looking for to get as an answer. I didn't though about trying the latest version, I'll do it in the meanwhile.

**Pull request closed without merging**
