### PR TITLE
[WIP] Add deploying website to CI

### PR DESCRIPTION
**Pull request by JoelMarcey**
Using Docusaurus and the Docusaurus Bot

### CODE REVIEW

**Comment by JoelMarcey** [comment]
This is currently a WIP - we need to add a call to the script that does the API docs, versioning, etc. I believe.

**Comment by kkashin** [comment]
@JoelMarcey - this won't run at the moment on Travis since deploy_website is not a supported directive, right? Just want to make sure we don't wipe what's on gh-pages

**Comment by JoelMarcey** [comment]
@kkashin - no. `gh-pages` has not been updated as a result of this PR.

**Comment by kkashin** [comment]
Cool, let's import and get this in then.

**Comment by JoelMarcey** [comment]
@kkashin So, if this actually lands as a commit to `.travis.yml`, then it *will* run as stated and call `yarn run gh-pages`. Do you want me to comment that part out for now? That's why I didn't want to land this yet until we got everything in order with the call to your script(s). But if I comment out that line, we can land it and then iterate via another PR. Either way.

**Comment by kkashin** [comment]
Ah, ok - let's either comment it out or just iterate on this PR until the scripts are called - either one!

**Pull request closed without merging**
